spring.application.name=AuthService
server.port=${PORT:8083}
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME:auth_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:Solano3030?}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET:JsLSl3fGbNVrZy1TzABfUKFhKIMAehJ6mx8pL0oNtu4=}
jwt.expiration=${JWT_EXPIRATION:86400000}
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.endpoints.web.cors.allowed-origins=${CORS_ORIGINS:http://localhost:5173}
management.endpoints.web.cors.allowed-methods=GET,POST,PUT,DELETE,PATCH
services.notification-url=${NOTIFICATION_URL:http://localhost:8086}
